/**
 * Scalar Design System — Mock Data
 * Single source of truth for firms, funds, companies, documents, and reports.
 */

const SCALAR_DB = {

  firms: [
    'Berkshire Partners Capital',
    'Blackstone Group',
    'KKR & Associates',
    'Apollo Global Management',
    'Carlyle Group',
    'TPG Capital Partners',
    'Warburg Pincus LLC',
    'General Atlantic',
    'Sequoia Capital',
    'Vista Equity Partners',
    'Advent International',
    'Bain Capital',
    'Thoma Bravo',
    'Silver Lake Partners',
    'Hellman & Friedman',
  ],

  funds: [
    'Growth Equity Fund III',
    'Buyout Fund IV',
    'Venture Capital Fund II',
    'Infrastructure Fund I',
    'Real Assets Fund 2021',
    'Credit Opportunities Fund',
    'Technology Growth Fund',
    'Healthcare Fund II',
    'Energy Transition Fund',
    'Fund XIII',
    'Property and Stakes 1',
    'Emerging Markets Fund',
    'Distressed Debt Fund',
    'Long-Short Equity Fund',
    'Multi-Strategy Fund 2022',
  ],

  companies: [
    'Airbus SAS',
    'ARAMCO Company',
    'Autopopulate Volatility Co.',
    'Berkshire Hathaway',
    'Blackstone, Inc.',
    'BTCHoldings (CAD)',
    'Cap Table Corp.',
    'Backsolve Technologies',
    'NovaTech Systems',
    'Meridian Healthcare',
    'Quantum Energy Ltd.',
    'Atlas Infrastructure',
    'Blue Ridge Capital',
    'DataStream Analytics',
    'Fusion Mobility',
    'GreenPath Renewables',
    'Ironclad Logistics',
    'Luminary Biotech',
    'Mosaic Financial',
    'Northstar Real Estate',
  ],

  documents: [
    // PDFs
    { name: 'Audited Financial Statements Q4 2024',   type: 'pdf'  },
    { name: 'Board Resolution – Series B Approval',   type: 'pdf'  },
    { name: 'Cap Table 12-31-2024',                   type: 'pdf'  },
    { name: 'Subscription Agreement – ARAMCO',        type: 'pdf'  },
    { name: 'Investment Committee Memo – BTCHoldings',type: 'pdf'  },
    { name: 'Fund Performance Summary 2024',          type: 'pdf'  },
    { name: 'Valuation Report Q3 2024 – Airbus',      type: 'pdf'  },
    { name: 'LP Quarterly Update Q4 2024',            type: 'pdf'  },
    { name: 'Portfolio Company Overview – Berkshire', type: 'pdf'  },
    { name: 'Operating Agreement Amendment 2023',     type: 'pdf'  },
    { name: 'Tax Return FY2023 – Fund XIII',          type: 'pdf'  },
    { name: 'Compliance Checklist Q2 2024',           type: 'pdf'  },
    { name: 'NDA – Blackstone Acquisition',           type: 'pdf'  },
    { name: 'Due Diligence Report – Fusion Mobility', type: 'pdf'  },
    { name: 'Annual Meeting Presentation 2024',       type: 'pdf'  },
    { name: 'Side Letter Agreement – LP Class A',     type: 'pdf'  },
    { name: 'Articles of Incorporation – NovaTech',   type: 'pdf'  },
    { name: 'Confidentiality Agreement – Atlas',      type: 'pdf'  },
    { name: 'Management Fee Schedule 2024',           type: 'pdf'  },
    { name: 'KYC Documentation – Luminary Biotech',   type: 'pdf'  },
    { name: 'Shareholder Rights Agreement',           type: 'pdf'  },
    { name: 'Exit Memo – DataStream Analytics',       type: 'pdf'  },
    { name: 'Board Meeting Minutes March 2024',       type: 'pdf'  },
    { name: 'Investor Report Q1 2024',                type: 'pdf'  },
    { name: 'Risk Management Policy 2024',            type: 'pdf'  },
    { name: 'Legal Opinion – Mosaic Financial',       type: 'pdf'  },
    { name: 'Engagement Letter – Ironclad Logistics', type: 'pdf'  },
    { name: 'Environmental Compliance Report',        type: 'pdf'  },
    { name: 'Portfolio Summary Deck Q4 2024',         type: 'pdf'  },
    { name: 'Fund Closing Checklist – Fund IV',       type: 'pdf'  },
    // XLSXs
    { name: 'Waterfall Model – Property and Stakes',  type: 'xlsx' },
    { name: 'Co-Investment Analysis – NovaTech',      type: 'xlsx' },
    { name: 'Cap Table Model – GreenPath',            type: 'xlsx' },
    { name: 'IRR Sensitivity Analysis 2024',          type: 'xlsx' },
    { name: 'Fund Expense Tracker 2024',              type: 'xlsx' },
    { name: 'Distribution Schedule Q4 2024',          type: 'xlsx' },
    { name: 'MOIC Tracker – All Funds',               type: 'xlsx' },
    { name: 'Valuation Bridge – Meridian Healthcare', type: 'xlsx' },
    { name: 'Portfolio Returns Dashboard',            type: 'xlsx' },
    { name: 'Cash Flow Forecast 2025',                type: 'xlsx' },
    // Word docs
    { name: 'Investment Policy Statement',            type: 'docx' },
    { name: 'GP Clawback Agreement Draft',            type: 'docx' },
    { name: 'Term Sheet – Quantum Energy',            type: 'docx' },
    { name: 'Partnership Agreement Draft',            type: 'docx' },
    { name: 'Investor Letter Q3 2024',                type: 'docx' },
  ],

  reports: [
    // PDFs
    { name: 'Portfolio Performance Report Q4 2024',   type: 'pdf'  },
    { name: 'Annual Fund Summary 2023',               type: 'pdf'  },
    { name: 'IRR by Fund Analysis – All Vintages',    type: 'pdf'  },
    { name: 'Waterfall Distribution Schedule Q3',     type: 'pdf'  },
    { name: 'Gross Returns Summary 2024',             type: 'pdf'  },
    { name: 'LP Distribution Report Q4 2024',         type: 'pdf'  },
    { name: 'Co-Investment Performance Report',       type: 'pdf'  },
    { name: 'Benchmark Comparison 2024',              type: 'pdf'  },
    { name: 'Fund Expense Report FY2023',             type: 'pdf'  },
    { name: 'ESG Portfolio Report 2024',              type: 'pdf'  },
    { name: 'Capital Deployment Summary Q4',          type: 'pdf'  },
    { name: 'Portfolio Risk Assessment 2024',         type: 'pdf'  },
    { name: 'Realized Gains Report FY2023',           type: 'pdf'  },
    { name: 'Fund Vintage Year Comparison',           type: 'pdf'  },
    { name: 'Liquidity Analysis – Q3 2024',           type: 'pdf'  },
    { name: 'Sector Allocation Report 2024',          type: 'pdf'  },
    { name: 'Management Fee Report Q4 2024',          type: 'pdf'  },
    { name: 'Carried Interest Tracker 2024',          type: 'pdf'  },
    { name: 'Annual Investor Statement 2023',         type: 'pdf'  },
    { name: 'Portfolio Company KPI Report',           type: 'pdf'  },
    // XLSXs
    { name: 'IRR Analysis All Funds',                 type: 'xlsx' },
    { name: 'MOIC Tracker 2024',                      type: 'xlsx' },
    { name: 'NAV Bridge Report Q4',                   type: 'xlsx' },
    { name: 'Capital Account Statement 2024',         type: 'xlsx' },
    { name: 'Gross to Net Returns Model',             type: 'xlsx' },
    { name: 'Distribution Waterfall Model',           type: 'xlsx' },
    { name: 'Cash Flow Projections 2025',             type: 'xlsx' },
    { name: 'Portfolio Valuation Summary',            type: 'xlsx' },
    { name: 'Fee and Expense Analysis 2024',          type: 'xlsx' },
    { name: 'LP Commitment Schedule',                 type: 'xlsx' },
    { name: 'Unfunded Commitment Tracker',            type: 'xlsx' },
    { name: 'DPI and RVPI Dashboard',                 type: 'xlsx' },
    { name: 'Quarterly Cash Flow Bridge',             type: 'xlsx' },
    { name: 'Fund-Level Attribution Model',           type: 'xlsx' },
    { name: 'Co-Investment Return Analysis',          type: 'xlsx' },
    { name: 'TVPI Progression by Fund',               type: 'xlsx' },
    { name: 'Recycling Capital Schedule',             type: 'xlsx' },
    { name: 'FX Impact on Returns 2024',              type: 'xlsx' },
    { name: 'Management Company Expense Report',      type: 'xlsx' },
    { name: 'Annual Portfolio Benchmarking',          type: 'xlsx' },
  ],

};
